# Form implementation generated from reading ui file 'D:\GitHub\UEL-Course\MLBA\QTDesigner\36. LearnPyQtBarGraphPart6\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 771, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.myLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.myLayout.setContentsMargins(0, 0, 0, 0)
        self.myLayout.setObjectName("myLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 0, 181, 51))
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 470, 771, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBoxBackgroundGrid = QtWidgets.QCheckBox(parent=self.horizontalLayoutWidget)
        self.checkBoxBackgroundGrid.setObjectName("checkBoxBackgroundGrid")
        self.horizontalLayout.addWidget(self.checkBoxBackgroundGrid)
        self.checkBoxLegend = QtWidgets.QCheckBox(parent=self.horizontalLayoutWidget)
        self.checkBoxLegend.setObjectName("checkBoxLegend")
        self.horizontalLayout.addWidget(self.checkBoxLegend)
        self.pushButtonChartBackground = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButtonChartBackground.setObjectName("pushButtonChartBackground")
        self.horizontalLayout.addWidget(self.pushButtonChartBackground)
        self.comboBoxBarColor = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget)
        self.comboBoxBarColor.setObjectName("comboBoxBarColor")
        self.horizontalLayout.addWidget(self.comboBoxBarColor)
        self.pushButtonBarColor = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButtonBarColor.setObjectName("pushButtonBarColor")
        self.horizontalLayout.addWidget(self.pushButtonBarColor)
        self.pushButtonClose = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.horizontalLayout.addWidget(self.pushButtonClose)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#55aaff;\">Lucy Company</span></p></body></html>"))
        self.checkBoxBackgroundGrid.setText(_translate("MainWindow", "Background Grid"))
        self.checkBoxLegend.setText(_translate("MainWindow", "Legend"))
        self.pushButtonChartBackground.setText(_translate("MainWindow", "Chart Background"))
        self.pushButtonBarColor.setText(_translate("MainWindow", "Bar Color"))
        self.pushButtonClose.setText(_translate("MainWindow", "Close"))
