# Form implementation generated from reading ui file 'D:\GitHub\UEL-Course\MLBA\QTDesigner\24. LearnQTableWidgetPart3\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(516, 394)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 30, 451, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBoxChooseTable = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.comboBoxChooseTable.setObjectName("comboBoxChooseTable")
        self.gridLayout.addWidget(self.comboBoxChooseTable, 1, 1, 1, 1)
        self.labelChooseDatabase = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.labelChooseDatabase.setObjectName("labelChooseDatabase")
        self.gridLayout.addWidget(self.labelChooseDatabase, 0, 0, 1, 1)
        self.labelChooseTable = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.labelChooseTable.setObjectName("labelChooseTable")
        self.gridLayout.addWidget(self.labelChooseTable, 1, 0, 1, 1)
        self.lineEditChoosDatabase = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEditChoosDatabase.setObjectName("lineEditChoosDatabase")
        self.gridLayout.addWidget(self.lineEditChoosDatabase, 0, 1, 1, 1)
        self.pushButtonPickSQLite = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPickSQLite.sizePolicy().hasHeightForWidth())
        self.pushButtonPickSQLite.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\GitHub\\UEL-Course\\MLBA\\QTDesigner\\24. LearnQTableWidgetPart3\\images/ic_pickdatabase.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonPickSQLite.setIcon(icon)
        self.pushButtonPickSQLite.setObjectName("pushButtonPickSQLite")
        self.gridLayout.addWidget(self.pushButtonPickSQLite, 0, 2, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 120, 451, 181))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushFetchMore = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushFetchMore.setGeometry(QtCore.QRect(30, 310, 91, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushFetchMore.sizePolicy().hasHeightForWidth())
        self.pushFetchMore.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\GitHub\\UEL-Course\\MLBA\\QTDesigner\\24. LearnQTableWidgetPart3\\images/ic_fetchmore.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushFetchMore.setIcon(icon1)
        self.pushFetchMore.setObjectName("pushFetchMore")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 516, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vo Minh Thanh"))
        self.labelChooseDatabase.setText(_translate("MainWindow", "Choose Database:"))
        self.labelChooseTable.setText(_translate("MainWindow", "Choose Table:"))
        self.pushButtonPickSQLite.setText(_translate("MainWindow", "..."))
        self.pushFetchMore.setText(_translate("MainWindow", "Fetch More"))
