# Form implementation generated from reading ui file 'D:\GitHub\UEL-Course\MLBA\QTDesigner\30. LearnModelViewPart5\MainWindow.Ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 376)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEditFilter = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditFilter.setGeometry(QtCore.QRect(10, 30, 391, 20))
        self.lineEditFilter.setObjectName("lineEditFilter")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label.setObjectName("label")
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 60, 391, 241))
        self.tableView.setObjectName("tableView")
        self.pushButtonFilter = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonFilter.setGeometry(QtCore.QRect(10, 310, 75, 23))
        self.pushButtonFilter.setObjectName("pushButtonFilter")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 420, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Filter Name:"))
        self.pushButtonFilter.setText(_translate("MainWindow", "Filter Column"))
