# Form implementation generated from reading ui file 'D:\GitHub\UEL-Course\MLBA\QTDesigner\29. LearnModelViewPart4\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(278, 439)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 30, 256, 192))
        self.tableView.setObjectName("tableView")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 230, 251, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.labelID = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.labelID.setObjectName("labelID")
        self.gridLayout.addWidget(self.labelID, 0, 0, 1, 1)
        self.labelUnitPrice = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.labelUnitPrice.setObjectName("labelUnitPrice")
        self.gridLayout.addWidget(self.labelUnitPrice, 2, 0, 1, 1)
        self.labelName = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.labelName.setObjectName("labelName")
        self.gridLayout.addWidget(self.labelName, 1, 0, 1, 1)
        self.lineEditUnitPrice = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEditUnitPrice.setObjectName("lineEditUnitPrice")
        self.gridLayout.addWidget(self.lineEditUnitPrice, 2, 1, 1, 1)
        self.lineEditName = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEditName.setObjectName("lineEditName")
        self.gridLayout.addWidget(self.lineEditName, 1, 1, 1, 2)
        self.lineEditID = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEditID.setObjectName("lineEditID")
        self.gridLayout.addWidget(self.lineEditID, 0, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 278, 21))
        self.menubar.setObjectName("menubar")
        self.menuSystems = QtWidgets.QMenu(parent=self.menubar)
        self.menuSystems.setObjectName("menuSystems")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_from_Json = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\GitHub\\UEL-Course\\MLBA\\QTDesigner\\29. LearnModelViewPart4\\images/ic_importdatabase.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionImport_from_Json.setIcon(icon)
        self.actionImport_from_Json.setObjectName("actionImport_from_Json")
        self.actionExport_to_JSon = QtGui.QAction(parent=MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\GitHub\\UEL-Course\\MLBA\\QTDesigner\\29. LearnModelViewPart4\\images/ic_export.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionExport_to_JSon.setIcon(icon1)
        self.actionExport_to_JSon.setObjectName("actionExport_to_JSon")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\GitHub\\UEL-Course\\MLBA\\QTDesigner\\29. LearnModelViewPart4\\images/ic_exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionExit.setIcon(icon2)
        self.actionExit.setObjectName("actionExit")
        self.menuSystems.addAction(self.actionImport_from_Json)
        self.menuSystems.addAction(self.actionExport_to_JSon)
        self.menuSystems.addSeparator()
        self.menuSystems.addAction(self.actionExit)
        self.menubar.addAction(self.menuSystems.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelID.setText(_translate("MainWindow", "Product ID:"))
        self.labelUnitPrice.setText(_translate("MainWindow", "Unit Price:"))
        self.labelName.setText(_translate("MainWindow", "Product Name:"))
        self.menuSystems.setTitle(_translate("MainWindow", "Systems"))
        self.actionImport_from_Json.setText(_translate("MainWindow", "Import from Json"))
        self.actionExport_to_JSon.setText(_translate("MainWindow", "Export to JSon"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
