# Form implementation generated from reading ui file 'D:\GitHub\UEL-Course\MLBA\final_project\1. Coding\4. App\LoginScreen\LoginScreen.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(529, 194)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 501, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditUserName = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.gridLayout.addWidget(self.lineEditUserName, 3, 2, 1, 2)
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.gridLayout.addWidget(self.lineEditPassword, 4, 2, 1, 2)
        self.labelPassword = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.labelPassword.setObjectName("labelPassword")
        self.gridLayout.addWidget(self.labelPassword, 4, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight)
        self.labelUserName = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.labelUserName.setObjectName("labelUserName")
        self.gridLayout.addWidget(self.labelUserName, 3, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 3, 1, 1)
        self.pushButtonCreateAccount = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButtonCreateAccount.setObjectName("pushButtonCreateAccount")
        self.gridLayout.addWidget(self.pushButtonCreateAccount, 5, 2, 1, 1)
        self.labelTitle = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.labelTitle.setObjectName("labelTitle")
        self.gridLayout.addWidget(self.labelTitle, 0, 0, 1, 5)
        self.pushButtonLogIn = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonLogIn.sizePolicy().hasHeightForWidth())
        self.pushButtonLogIn.setSizePolicy(sizePolicy)
        self.pushButtonLogIn.setObjectName("pushButtonLogIn")
        self.gridLayout.addWidget(self.pushButtonLogIn, 5, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 529, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BMS"))
        self.labelPassword.setText(_translate("MainWindow", "Pasword:"))
        self.labelUserName.setText(_translate("MainWindow", "User Name:"))
        self.pushButtonCreateAccount.setText(_translate("MainWindow", "Create Account"))
        self.labelTitle.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; color:#55aaff;\">BMS - BAMOS Management Suite</span></p></body></html>"))
        self.pushButtonLogIn.setText(_translate("MainWindow", "Log In"))
