# Form implementation generated from reading ui file 'D:\GitHub\UEL-Course\MLBA\QTDesigner\14. LearnCheckbox\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(327, 334)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(21, 60, 281, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.labelEmail = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.labelEmail.setObjectName("labelEmail")
        self.gridLayout.addWidget(self.labelEmail, 1, 0, 1, 1)
        self.labelFullName = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.labelFullName.setObjectName("labelFullName")
        self.gridLayout.addWidget(self.labelFullName, 0, 0, 1, 1)
        self.lineEditFullName = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditFullName.sizePolicy().hasHeightForWidth())
        self.lineEditFullName.setSizePolicy(sizePolicy)
        self.lineEditFullName.setObjectName("lineEditFullName")
        self.gridLayout.addWidget(self.lineEditFullName, 0, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.labelCourseRegistration = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelCourseRegistration.setGeometry(QtCore.QRect(21, 20, 281, 31))
        self.labelCourseRegistration.setObjectName("labelCourseRegistration")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 140, 171, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelCourseSelection = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCourseSelection.sizePolicy().hasHeightForWidth())
        self.labelCourseSelection.setSizePolicy(sizePolicy)
        self.labelCourseSelection.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.labelCourseSelection.setAutoFillBackground(False)
        self.labelCourseSelection.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.labelCourseSelection.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelCourseSelection.setObjectName("labelCourseSelection")
        self.verticalLayout.addWidget(self.labelCourseSelection)
        self.checkBoxMachineLearning = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBoxMachineLearning.setObjectName("checkBoxMachineLearning")
        self.verticalLayout.addWidget(self.checkBoxMachineLearning)
        self.checkBoxDeepLearning = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBoxDeepLearning.setObjectName("checkBoxDeepLearning")
        self.verticalLayout.addWidget(self.checkBoxDeepLearning)
        self.checkBoxSmartContract = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBoxSmartContract.setObjectName("checkBoxSmartContract")
        self.verticalLayout.addWidget(self.checkBoxSmartContract)
        self.pushButtonSubmit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSubmit.setGeometry(QtCore.QRect(160, 240, 75, 23))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\GitHub\\UEL-Course\\MLBA\\QTDesigner\\14. LearnCheckbox\\image/ic_send.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSubmit.setIcon(icon)
        self.pushButtonSubmit.setObjectName("pushButtonSubmit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 327, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Võ Minh Thành"))
        self.labelEmail.setText(_translate("MainWindow", "Email:"))
        self.labelFullName.setText(_translate("MainWindow", "Full Name:"))
        self.labelCourseRegistration.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#55aaff;\">COURSES REGISTRATION </span></p></body></html>"))
        self.labelCourseSelection.setText(_translate("MainWindow", "<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"    <style>\n"
"        p {\n"
"            background-color: #aaaaff;\n"
"            padding: 5px;\n"
"            border-radius: 5px;\n"
"            text-align: center; \n"
"        }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <p><span style=\"font-size:12pt; font-weight:600; color:#00aa7f;\">Course Selection:</span></p>\n"
"</body>\n"
"</html>\n"
""))
        self.checkBoxMachineLearning.setText(_translate("MainWindow", "Machine Learning"))
        self.checkBoxDeepLearning.setText(_translate("MainWindow", "Deep Learning"))
        self.checkBoxSmartContract.setText(_translate("MainWindow", "Smart Contract"))
        self.pushButtonSubmit.setText(_translate("MainWindow", "Submit"))
